<a href="https://colab.research.google.com/github/ankitrajput77/google_colab/blob/main/01_tensor_constant_and_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf








# Constant

In [2]:
tensor_0_d = tf.constant(4)
tensor_0_d

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [3]:
tensor_1_d = tf.constant([1, 2, 3, 4.])
tensor_1_d

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [4]:
tensor_2_d = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7 ,8]
    ], dtype='float64')
tensor_2_d

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])>

In [5]:
tensor_2_d_numpy_array = tensor_2_d.numpy()
tensor_2_d_numpy_array

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [6]:
type(tensor_2_d_numpy_array)

numpy.ndarray

In [7]:
tensor_3_d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_3_d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [8]:
tensor_3_d.shape

TensorShape([2, 2, 2])

In [9]:
tensor_4_d = tf.constant([[[[10, 20], [30, 40]], [[50, 60], [70, 80]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
tensor_4_d

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[10, 20],
         [30, 40]],

        [[50, 60],
         [70, 80]]],


       [[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]]], dtype=int32)>

In [10]:
# Casting
x = tf.constant([1.8, 2.2], dtype=tf.float32)
tf.cast(x, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [11]:
tensor_string = tf.constant("hello")
tensor_string # b before the string indicates that the string is represented as a byte string.

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [12]:
import numpy as np

In [13]:
x = np.array([1 ,2, 3, 4])

In [14]:
tensor_from_numpy = tf.convert_to_tensor(x)
tensor_from_numpy

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [15]:
# identity matrix
tensor_eye = tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=[1, 2],
    dtype=tf.int16,
    name='identity'
)

In [16]:
tensor_eye

<tf.Tensor: shape=(1, 2, 3, 3), dtype=int16, numpy=
array([[[[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]],

        [[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]]]], dtype=int16)>

In [17]:
tensor_eye.ndim

4

In [18]:
diagonal_tensor = 4*tensor_eye
print(diagonal_tensor)

tf.Tensor(
[[[[4 0 0]
   [0 4 0]
   [0 0 4]]

  [[4 0 0]
   [0 4 0]
   [0 0 4]]]], shape=(1, 2, 3, 3), dtype=int16)


In [19]:
tensor_fill = tf.fill([4, 3], 9.)
tensor_fill

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]], dtype=float32)>

In [20]:
tensor_ones = tf.ones([2, 3], 9)
tensor_ones

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [21]:



tensor_random = tf.random.normal([3, 3], # this follows normal distribution
                                 mean=5.0, # approx values
                                 stddev=0.1, # values are (mean - std , mean + std)
                                 dtype=tf.float32,
                                 seed=None,
                                 name=None)
tensor_random

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[4.9207087, 4.9630938, 5.1059675],
       [5.0536613, 5.045946 , 5.054727 ],
       [4.9156847, 4.8046436, 5.079447 ]], dtype=float32)>

In [22]:
tf.random.set_seed(5)
tensor_uniform = tf.random.uniform([3, 2],
                                   minval=0,
                                   maxval=1,
                                   dtype=tf.float32,
                                   seed=10,
                                   name=None)
tensor_uniform

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.09164894, 0.95672214],
       [0.02972937, 0.7234143 ],
       [0.74135363, 0.04138255]], dtype=float32)>

In [23]:
tf.random.set_seed(5) # global random seed
tf.random.uniform([3],
                                   minval=0,
                                   maxval=1,
                                   dtype=tf.float32,
                                   seed=10, # local operation seed
                                   name=None)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.09164894, 0.95672214, 0.02972937], dtype=float32)>

In [24]:
#indexing can be done in tensors
tensor_4_d[0:2, 0:2, 0:2, 0:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[10, 20],
         [30, 40]],

        [[50, 60],
         [70, 80]]],


       [[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]]], dtype=int32)>

In [25]:
tensor_complex = tf.constant([[-1+2j], [-4+6j]])
tensor_complex
tf.abs(tensor_complex) # (sqrt(-1^2 + 2^2)) (sqrt(-4^2 + 6^2))

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[2.23606798],
       [7.21110255]])>

In [26]:
print(tf.math.add([3, 2, 1] ,[1, 2, 3]))
print(tf.math.subtract([3, 2, 1] ,[1, 2, 3]))
print(tf.math.divide([3, 2, 1] ,[1, 2, 3]))
print(tf.math.multiply([3, 2, 1] ,[1, 2, 3]))

tf.Tensor([4 4 4], shape=(3,), dtype=int32)
tf.Tensor([ 2  0 -2], shape=(3,), dtype=int32)
tf.Tensor([3.         1.         0.33333333], shape=(3,), dtype=float64)
tf.Tensor([3 4 3], shape=(3,), dtype=int32)


In [27]:
tensor_argmax = tf.constant([1, 2, 3, 4, 5])
tf.math.argmax(tensor_argmax) # gives index of max value

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [28]:
x = tf.constant([[3, 4], [1, 2]])
y = tf.constant([[2, 3], [4, 5]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 64],
       [ 1, 32]], dtype=int32)>

In [29]:
tf.math.reduce_sum(tf.constant([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]), axis=0, keepdims=False, name=None)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4,  8, 12, 16], dtype=int32)>

In [30]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>

In [31]:
input = tf.random.normal(shape=(2, 2))
k = 1
values, indices  = tf.math.top_k(input, k=k)
input

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.18030666, -0.95028627],
       [-0.03964049, -0.7425406 ]], dtype=float32)>

In [32]:
values.shape == indices.shape == input.shape[:-1] + [k]

True

In [33]:
values

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.18030666],
       [-0.03964049]], dtype=float32)>

In [34]:
# matrix multiplication
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False, # conjjugate and tranpose before mul
    adjoint_b=False,
    a_is_sparse=False, # larges number of zeros present in matrix
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [35]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [36]:
tf.transpose(a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [37]:
# LOWER TRIANGULAR MATRIX
tf.linalg.band_part(tensor_2_d, -1, 0)

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[1., 0., 0., 0.],
       [5., 6., 0., 0.]])>

In [38]:
# UPPER TRIANGULAR MATRIX
tf.linalg.band_part(tensor_2_d, 0, -1)

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[1., 2., 3., 4.],
       [0., 6., 7., 8.]])>

In [39]:
# DIAGONAL MATRIX
tf.linalg.band_part(tensor_2_d, 0, 0)

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[1., 0., 0., 0.],
       [0., 6., 0., 0.]])>

In [40]:
tf.linalg.inv([[1, 2.],[3, 4]]) # remember to have float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [41]:
tf.linalg.trace([[1, 2.],[3, 4]])

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [47]:
# matrix mul
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
e = tf.einsum('ij,jk->ik', a, b)
print(e.shape)
print(e)

(2, 2)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [50]:
# matrix mul
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[2, 3])
e = tf.einsum('ij,kj->ik', a, b) # ( a*b^t )
print(e.shape)
print(e)

(2, 2)
tf.Tensor(
[[ 50  68]
 [122 167]], shape=(2, 2), dtype=int32)


In [53]:
import numpy as np
A = np.random.randn(2, 4, 4, 2)
B = np.random.randn(2, 4, 4, 1)
np.einsum("bcik, bcij -> bckj", A, B).shape

(2, 4, 2, 1)

In [55]:
# remove dimension of size 1
t = np.random.randn(1, 2, 1, 3, 1, 1)
tf.shape(tf.squeeze(t, [2, 4]))  # [1, 2, 3, 1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 1], dtype=int32)>

In [62]:
image = tf.zeros([10,10,3])
print(image.shape)
print(tf.expand_dims(image, axis=1).shape.as_list())
print(tf.expand_dims(image, axis=3).shape.as_list())

(10, 10, 3)
[10, 1, 10, 3]
[10, 10, 3, 1]


# Ragged Tensor

In [69]:
A = [
    [2, 3],
    [5, 6, 7],
    [1,],
    [8, 9, 0, 0]
]
tensor_ragged = tf.ragged.constant(A)
print(tensor_ragged)
print(tensor_ragged.shape)

<tf.RaggedTensor [[2, 3], [5, 6, 7], [1], [8, 9, 0, 0]]>
(4, None)


In [74]:
tf.ragged.boolean_mask(  # Mask a 2D Tensor.
data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
mask=[[True, False, True], [False, False, False], [True, False, False]])

<tf.RaggedTensor [[1, 3], [], [7]]>

In [76]:
tf.ragged.boolean_mask(  # Mask rows of a 2D RaggedTensor.
tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
tf.ragged.constant([True, False, True]))

<tf.RaggedTensor [[1, 2, 3], [5, 6]]>

In [78]:
tf.ragged.cross([tf.ragged.constant([['a'], ['b', 'c']]),
                 tf.ragged.constant([['d'], ['e']]),
                 tf.ragged.constant([['f'], ['g']])]).to_list()

[[b'a_X_d_X_f'], [b'b_X_e_X_g', b'c_X_e_X_g']]

In [79]:
tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

# Variables

In [81]:
v = tf.Variable(1.)
v.assign(2.)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [82]:
v = tf.Variable(1., shape=tf.TensorShape(None))
v.assign([[1.]])

<tf.Variable 'UnreadVariable' shape=<unknown> dtype=float32, numpy=array([[1.]], dtype=float32)>